### PR TITLE
Allow to create copy of a controller profile under new name

### PR DESCRIPTION
**Pull request by vicocz**
I needed such function to create a profile based on the existing one e.g. to reduce some events for smaller kids during an LEGO exhibition.
The COPY icon was taken from this set: https://www.flaticon.com/free-icon/copy_126498

### CODE REVIEW

**Comment by vicocz** [comment]
BC2- Copy profile

**Comment by vicocz** [comment]
Seems this is going to be implemented here: https://github.com/imurvai/brickcontroller2/compare/ProfileLoadSave

**Comment by imurvai** [comment]
Yes, I'm looking for options to be able to load and save profiles to/from file system or network.

**Comment by vicocz** [comment]
Possible to be done via Export / Import

**Comment by imurvai** [comment]
Yes, I've implemented the profile load/save from/to local folder but it seems this way has been closed in Android 10, so I need to find a way to load/save using google drive eg.

**Pull request closed without merging**
