### PR TITLE
Basic support for Buwizz3 servo and stepper + UI adjustments

### PR DESCRIPTION
**Pull request by vicocz**
Servo and stepper behavior has been partially copy-pasted from PU device. Additionally adjusted UI to support PU only.
When action is configured as SERVO, PU absolute positioning mode is used.  For STEPPER relative position is initialized after connection and increased. Both required proper PU motor.
Neither servo calibration nor reset is part of this PR. 
Still not sure if API is used properly as servo/stepper configured motor(s) are whistling little bit. And possibly stepper initialization seems to be fragile.

### CODE REVIEW

**Comment by imurvai** [comment]
Hi,
This is pretty cool you started figuring out the full BW3 support. As I still don't have any BW3 device it would be harder for me to implement it properly.
Tomorrow I'll try to check your changes, but last week I had a surgery so maybe it'll take longer.
Many thanks for your contribution so far! :)

**Comment by DenoG1997** [comment]
get well soon im waiting für servo update for thema Bw3. i have one can i help you ?

**Comment by vicocz** [comment]
I've just simplified timestamps of position updates as they come together in bulk in comparison to notifications used in `ControlPlusDevice`.

@imurvai Wish u fast recovery. Feel free to modify this PR as needed.

**Comment by vicocz** [comment]
Changed to DRAFT as I tried to check Buwizz3 on Android and the stepper was not working properly.

**Comment by vicocz** [comment]
Fortunatelly some progress after days of tries and failures. Seems from an unknown reason writes of characteristic were usually not successfull on Android if `EnableNotificationAsync` was called before motors have been configured. Weired as it was OK when running BC2 on Windows.
Therefore moved it from `ValidateServicesAsync` to `AfterConnectSetupAsync`.
Additionally adjusted handling of channel values so as servro motor is able to turn in a partial angle e.g. for a gamepad axis value of `0.5`.
IMHO it works pretty well now. Would be nice if someone can test it as well.

**Comment by DenoG1997** [comment]
> Fortunatelly some progress after days of tries and failures. Seems from an unknown reason writes of characteristic were usually not successfull on Android if `EnableNotificationAsync` was called before motors have been configured. Weired as it was OK when running BC2 on Windows.
> Therefore moved it from `ValidateServicesAsync` to `AfterConnectSetupAsync`.
> Additionally adjusted handling of channel values so as servro motor is able to turn in a partial angle e.g. for a gamepad axis value of `0.5`.
> IMHO it works pretty well now. Would be nice if someone can test it as well.

i can test ist in ios when you tell me how i install it😅

**Comment by imurvai** [comment]
I'm merging it to master. Thanks for adding it.
For iOS I'll try to push it to TestFlight soon, and for android I'll put the apk to dropbox to test.

**Comment by DenoG1997** [comment]
Can you tell me the inviting code for test flight ?

**Comment by DenoG1997** [comment]
How can I get access to TestFlight ?

**Pull request merged**
